#pragma once

#include <QDir>
#include <QFile>
#include <QString>
#include <QTemporaryFile>

namespace trailer {

// Reserve a unique writable path under QDir::tempPath(). The reserved
// file is removed before this function returns, so external writers
// (qpdf's QPDFWriter, etc.) can open the path with exclusive write
// access. The caller owns cleanup of whatever it writes to the path.
//
// Why not QTemporaryFile? On Windows, QTemporaryFile keeps the
// underlying file handle alive past close() so its destructor can
// auto-remove it. The held handle's share mode conflicts with
// fopen(path, "wb"), so a subsequent qpdf write fails with EACCES /
// "Permission denied". Linux + macOS don't enforce that share
// semantic, which is why the bug doesn't show up there.
//
// `templateName` is a filename-only template (no directory). It must
// contain "XXXXXX" for QTemporaryFile's unique-suffix generator.
inline QString makeUniqueTempPath(const QString &templateName) {
    QTemporaryFile probe(QDir::tempPath() + QStringLiteral("/") + templateName);
    probe.setAutoRemove(false);
    if (!probe.open())
        return {};
    const QString path = probe.fileName();
    probe.close();
    QFile::remove(path);
    return path;
}

// Owns a temp path generated by makeUniqueTempPath() and removes
// whatever file lives at that path on destruction. Move-only.
class ScopedTempFile {
  public:
    ScopedTempFile() = default;
    explicit ScopedTempFile(const QString &templateName)
        : m_path(makeUniqueTempPath(templateName)) {}
    ~ScopedTempFile() {
        if (!m_path.isEmpty())
            QFile::remove(m_path);
    }

    ScopedTempFile(const ScopedTempFile &) = delete;
    ScopedTempFile &operator=(const ScopedTempFile &) = delete;

    ScopedTempFile(ScopedTempFile &&other) noexcept : m_path(std::move(other.m_path)) {
        other.m_path.clear();
    }
    ScopedTempFile &operator=(ScopedTempFile &&other) noexcept {
        if (this != &other) {
            if (!m_path.isEmpty())
                QFile::remove(m_path);
            m_path = std::move(other.m_path);
            other.m_path.clear();
        }
        return *this;
    }

    bool isValid() const { return !m_path.isEmpty(); }
    const QString &path() const { return m_path; }

  private:
    QString m_path;
};

} // namespace trailer
