#!/bin/bash
set -e
if [ "$1" = "configure" ]; then
    update-desktop-database -q /usr/share/applications || true
    update-mime-database /usr/share/mime || true
    xdg-icon-resource forceupdate --theme hicolor 2>/dev/null || true
fi
