#!/usr/bin/env python3
"""Generate a WiX 3.x DllComponents.wxs fragment from a build-windows/ directory.

Usage:
    python3 generate-wix-fragment.py [build-dir]

  build-dir defaults to "build-windows/" relative to the repo root
  (the script locates the repo root as two directories up from itself).

Output:
    platform/windows/DllComponents.wxs  (next to this script)

The fragment contains one <Component> per file found in build-dir,
excluding trailer.exe and platforms/qwindows.dll (both handled in
the hand-authored trailer.wxs).

GUIDs are deterministic: uuid.uuid5(NAMESPACE_DNS, relative_path)
so repeated runs produce the same .wxs and don't trigger unnecessary
installer upgrades.
"""

import re
import sys
import uuid
from collections import defaultdict
from pathlib import Path

# ── Paths ──────────────────────────────────────────────────────────────────

SCRIPT_DIR = Path(__file__).resolve().parent   # platform/windows/
REPO_ROOT  = SCRIPT_DIR.parent.parent          # repo root


def resolve_build_dir() -> Path:
    if len(sys.argv) > 1:
        p = Path(sys.argv[1])
        return p if p.is_absolute() else Path.cwd() / p
    return REPO_ROOT / "build-windows"


BUILD_DIR  = resolve_build_dir()
OUTPUT_WXS = SCRIPT_DIR / "DllComponents.wxs"

# Files handled explicitly in trailer.wxs — exclude by forward-slash relative path.
EXCLUDED_REL = {
    "trailer.exe",
    "platforms/qwindows.dll",
}

# ── Helpers ────────────────────────────────────────────────────────────────

_NON_IDENT = re.compile(r"[^A-Za-z0-9]")


def _sanitize(rel_path: str, prefix: str) -> str:
    """Return a valid WiX identifier for a relative file path."""
    safe = _NON_IDENT.sub("_", rel_path)
    # WiX identifiers max 72 chars; truncate from the left to keep the suffix unique
    if len(safe) > 60:
        safe = safe[-60:]
    return prefix + safe


def wix_component_id(rel_path: str) -> str:
    return _sanitize(rel_path, "Dll_")


def wix_dir_id(rel_dir: str) -> str:
    return _sanitize(rel_dir, "Dir_") if rel_dir else "TrailerFolder"


def deterministic_guid(rel_path: str) -> str:
    """Return a WiX-formatted GUID derived from the file's normalised relative path."""
    raw = uuid.uuid5(uuid.NAMESPACE_DNS, rel_path.replace("\\", "/").lower())
    return "{" + str(raw).upper() + "}"


# ── Walk the build directory ────────────────────────────────────────────────

if not BUILD_DIR.exists():
    print(f"ERROR: build directory not found: {BUILD_DIR}", file=sys.stderr)
    print("Run scripts/build-windows.sh first, or pass the path as an argument.", file=sys.stderr)
    sys.exit(1)

# Collect (rel_fwd, abs_path) for every file except the explicitly excluded ones.
files: list[tuple[str, Path]] = []
for abs_path in sorted(BUILD_DIR.rglob("*")):
    if not abs_path.is_file():
        continue
    rel_fwd = abs_path.relative_to(BUILD_DIR).as_posix()
    if rel_fwd in EXCLUDED_REL:
        continue
    files.append((rel_fwd, abs_path))

# ── Group files by sub-directory ───────────────────────────────────────────

by_dir: dict[str, list[tuple[str, Path]]] = defaultdict(list)
for rel_fwd, abs_path in files:
    parent = str(Path(rel_fwd).parent)
    by_dir["" if parent == "." else parent].append((rel_fwd, abs_path))

# ── Build WiX XML ──────────────────────────────────────────────────────────

WIX_NS = "http://schemas.microsoft.com/wix/2006/wi"

lines: list[str] = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    "<!-- Auto-generated by generate-wix-fragment.py — do not edit by hand -->",
    f'<Wix xmlns="{WIX_NS}">',
    "  <Fragment>",
]

component_ids: list[str] = []

for dir_rel, dir_files in sorted(by_dir.items()):
    dir_ref_id = wix_dir_id(dir_rel)
    lines.append(f'    <DirectoryRef Id="{dir_ref_id}">')

    for rel_fwd, abs_path in dir_files:
        comp_id   = wix_component_id(rel_fwd)
        comp_guid = deterministic_guid(rel_fwd)
        file_id   = comp_id + "_File"
        source    = f"build-windows/{rel_fwd}"

        lines.append(f'      <Component Id="{comp_id}" Guid="{comp_guid}">')
        lines.append(f'        <File Id="{file_id}" Source="{source}" KeyPath="yes" />')
        lines.append(f'      </Component>')
        component_ids.append(comp_id)

    lines.append("    </DirectoryRef>")

lines += [
    "",
    '    <ComponentGroup Id="DllComponents">',
    *[f'      <ComponentRef Id="{cid}" />' for cid in component_ids],
    "    </ComponentGroup>",
    "  </Fragment>",
    "</Wix>",
]

# ── Write output ────────────────────────────────────────────────────────────

OUTPUT_WXS.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Wrote {len(component_ids)} component(s) to {OUTPUT_WXS}")
