// grab_screenshots — produce reference PNGs of Trailer's main window
// states by driving Application + MainWindow under the offscreen Qt
// platform plugin. Used to populate docs/screenshots/ for the
// Windows documentation set without needing an active desktop session
// (works fine over SSH, in CI, etc.).
//
// Usage:
//   ./grab_screenshots <output-dir>
//
// On Windows the caller must set QT_QPA_FONTDIR=%SystemRoot%\Fonts so
// QPdfWriter has access to real PDF fonts; otherwise the fixture-PDF
// shot will show characters rendered as filled paths. See the comment
// in tests/uat/CMakeLists.txt for the longer explanation.
//
// Output files (under <output-dir>):
//   01-empty-window.png        empty MainWindow, no document loaded
//   02-pdf-loaded.png          fixture PDF loaded in the viewer
//   prefs-<tab>.png            Preferences dialog, one shot per tab
//                              (General/Files/Machine Learning/Advanced).
//                              The Machine Learning and Advanced shots
//                              double as the disabled-control-with-tooltip
//                              evidence: with no host callbacks wired the
//                              "Manage models…" and "Reset all…" buttons
//                              stay disabled and carry their explanatory
//                              tooltips, and the General tab shows the
//                              disabled Theme combo + helper label.
//
// The window is sized 1280x800 — a desktop-ish ratio that fits the
// toolbar + sidebar + viewer layout legibly while remaining portable
// across documentation surfaces.

#include "app/Application.h"
#include "ui/EmptyStateWidget.h"
#include "ui/MainWindow.h"
#include "ui/PreferencesDialog.h"

#include <QAction>
#include <QDir>
#include <QMenu>
#include <QTabWidget>
#include <QElapsedTimer>
#include <QFileInfo>
#include <QImage>
#include <QPainter>
#include <QPageSize>
#include <QPdfWriter>
#include <QString>
#include <QStringList>
#include <QTemporaryDir>
#include <QThread>
#include <QTimer>
#include <cstdio>

namespace {

QString writeFixturePdf(const QString &path) {
    // Two-page A4 fixture with realistic-looking body text so the
    // resulting screenshot is recognisable as a document viewer.
    QPdfWriter writer(path);
    writer.setPageSize(QPageSize(QPageSize::A4));
    QPainter p(&writer);
    QFont title;
    title.setPointSize(28);
    title.setBold(true);
    p.setFont(title);
    p.drawText(300, 600, QStringLiteral("Trailer on Windows"));
    QFont body;
    body.setPointSize(14);
    p.setFont(body);
    p.drawText(300, 1000,
               QStringLiteral("A cross-platform PDF and image workbench."));
    p.drawText(300, 1300,
               QStringLiteral("This fixture is generated by tools/grab_screenshots."));
    writer.newPage();
    p.setFont(title);
    p.drawText(300, 600, QStringLiteral("Page 2"));
    p.setFont(body);
    p.drawText(300, 1000,
               QStringLiteral("Demonstrates multi-page navigation in the viewer."));
    p.end();
    return path;
}

// Pump the event loop until either `pred()` returns true or the
// timeout elapses. Used to wait for asynchronous side effects (PDF
// load → first paint, signal-driven layout updates) to settle before
// the grab. Returns true if `pred` ever returned true.
template <typename Pred> bool waitFor(Pred pred, int timeoutMs = 2000) {
    QElapsedTimer timer;
    timer.start();
    while (!pred() && timer.elapsed() < timeoutMs) {
        QCoreApplication::processEvents(QEventLoop::AllEvents, 50);
        QThread::msleep(10);
    }
    return pred();
}

bool grabAndSave(QWidget *w, const QString &outPath) {
    // One more spin so any pending paints flush through before grab.
    QCoreApplication::processEvents();
    const QPixmap pm = w->grab();
    if (pm.isNull()) {
        std::fprintf(stderr, "grab returned null pixmap for %s\n",
                     outPath.toLocal8Bit().constData());
        return false;
    }
    if (!pm.save(outPath)) {
        std::fprintf(stderr, "failed to write %s\n",
                     outPath.toLocal8Bit().constData());
        return false;
    }
    std::printf("wrote %s (%dx%d)\n",
                outPath.toLocal8Bit().constData(), pm.width(), pm.height());
    return true;
}

// Build the real File → Screenshot submenu via Application::addAcquireItems
// with INJECTED capability inputs (platformName + underWaylandSession), then
// grab it offscreen. This is the sanctioned G2 method (QWidget::grab of the
// real control) — the injection seam lets us drive the Wayland disabled state
// under the offscreen plugin, where QGuiApplication::platformName() would
// otherwise always be "offscreen" (→ Whole Screen enabled).
//
// NOTE: the honest tooltip on the disabled Whole Screen item is a hover-
// transient QToolTip in a separate top-level window, so it is NOT part of the
// menu->grab() pixmap. Its exact string is asserted in the unit test
// (tests/test_linux_capture_capability.cpp::unavailableMessageIsHonest). The
// greyed-out item itself is real in the grab.
bool grabCaptureMenu(trailer::Application &app, QWidget *ctx, const QString &platformName,
                     bool underWaylandSession, const QString &outPath) {
    // Parent menu is a throwaway File menu; addAcquireItems adds the Screenshot
    // submenu (Whole Screen / Window / Selected Area) plus Scanner / Camera.
    QMenu fileMenu;
    app.addAcquireItems(&fileMenu, ctx, platformName, underWaylandSession);

    // The Screenshot submenu is the first action carrying a submenu.
    QMenu *screenshotMenu = nullptr;
    for (QAction *a : fileMenu.actions()) {
        if (a->menu()) {
            screenshotMenu = a->menu();
            break;
        }
    }
    if (!screenshotMenu) {
        std::fprintf(stderr, "Screenshot submenu not found for %s\n",
                     outPath.toLocal8Bit().constData());
        return false;
    }
    // Popup offscreen so the menu lays out its items at a real size, then grab.
    screenshotMenu->popup(QPoint(0, 0));
    app.processEvents();
    const QPixmap pm = screenshotMenu->grab();
    screenshotMenu->close();
    app.processEvents();
    if (pm.isNull()) {
        std::fprintf(stderr, "grab returned null pixmap for %s\n",
                     outPath.toLocal8Bit().constData());
        return false;
    }
    if (!pm.save(outPath)) {
        std::fprintf(stderr, "failed to write %s\n", outPath.toLocal8Bit().constData());
        return false;
    }
    std::printf("wrote %s (%dx%d)\n", outPath.toLocal8Bit().constData(), pm.width(), pm.height());
    return true;
}

} // namespace

int main(int argc, char **argv) {
    if (argc < 2) {
        std::fprintf(stderr, "usage: %s <output-dir>\n", argv[0]);
        return 2;
    }
    const QString outDir = QString::fromUtf8(argv[1]);
    QDir().mkpath(outDir);

    trailer::Application app(argc, argv);
    Q_INIT_RESOURCE(trailer);

    // Fixture PDF lives in a QTemporaryDir cleaned up at exit.
    QTemporaryDir scratch;
    if (!scratch.isValid()) {
        std::fprintf(stderr, "failed to create scratch dir\n");
        return 1;
    }
    const QString fixturePath = writeFixturePdf(scratch.filePath("fixture.pdf"));

    auto *mw = app.ensureWindow();
    if (!mw) {
        std::fprintf(stderr, "ensureWindow() returned null\n");
        return 1;
    }
    mw->resize(1280, 800);
    app.processEvents();

    if (!grabAndSave(mw, QDir(outDir).filePath(QStringLiteral("01-empty-window.png")))) {
        return 1;
    }

    // Empty-state window model shots. A freshly-spawned window with no
    // document shows the EmptyStateWidget welcome surface.
    if (!grabAndSave(mw, QDir(outDir).filePath(QStringLiteral("empty-state.png")))) {
        return 1;
    }

    // Same window with the drag-highlight active, so the reference set
    // captures the drop-target affordance the user sees mid-drag.
    if (auto *empty = mw->findChild<trailer::EmptyStateWidget *>()) {
        empty->setDragHighlighted(true);
        app.processEvents();
        if (!grabAndSave(mw, QDir(outDir).filePath(QStringLiteral("empty-state-drag.png")))) {
            return 1;
        }
        empty->setDragHighlighted(false);
        app.processEvents();
    } else {
        std::fprintf(stderr, "EmptyStateWidget not found — cannot grab empty-state-drag.png\n");
        return 1;
    }

    app.openFiles({fixturePath});

    // openFiles may spawn an additional window depending on the
    // user's OpenFilesIn preference. Find the most-recently-created
    // MainWindow (the one that just got the document) and wait for
    // QPdfDocument's asynchronous load + first paint cycle before we
    // grab. Without the wait the PDF render area is still blank,
    // making the "PDF loaded" screenshot indistinguishable from the
    // empty one.
    QWidget *target = mw;
    for (auto *w : trailer::Application::topLevelWidgets()) {
        if (auto *candidate = qobject_cast<trailer::MainWindow *>(w)) {
            candidate->resize(1280, 800);
            target = candidate;
        }
    }

    // Give the document time to load + render. QPdfDocument's lazy
    // page render lands on the GUI thread via signal so processEvents
    // alone is enough — the timeout is generous so a slow first-run
    // FreeType init doesn't make this flaky.
    waitFor(
        [target]() {
            return target->windowTitle().contains(QStringLiteral("fixture")) ||
                   target->windowTitle().contains(QStringLiteral("Trailer"));
        },
        3000);

    // One more grace period so QPdfView's pixmap caches populate.
    waitFor([] { return false; }, 500);

    if (!grabAndSave(target, QDir(outDir).filePath(QStringLiteral("02-pdf-loaded.png")))) {
        return 1;
    }

    // Empty-state window model: a window with a document open shows the
    // document view (empty state swapped out).
    if (!grabAndSave(target, QDir(outDir).filePath(QStringLiteral("doc-loaded.png")))) {
        return 1;
    }

    // Preferences dialog — one shot per tab. We construct it against the
    // live Settings and deliberately DO NOT wire the Manage-models /
    // Reset-all callbacks: that leaves those buttons disabled (with the
    // explanatory tooltips) so the Machine Learning and Advanced shots
    // double as the disabled-control evidence, and the General tab shows
    // the disabled Theme combo + helper label. The dialog is rendered
    // offscreen via grab(); it is never exec()'d, so this stays headless.
    {
        auto *prefs = new trailer::PreferencesDialog(app.settings(), target);
        prefs->resize(720, 560);
        prefs->show();
        app.processEvents();
        auto *tabs = prefs->findChild<QTabWidget *>(QStringLiteral("tabWidget"));
        if (!tabs) {
            std::fprintf(stderr, "Preferences tab widget not found — cannot grab prefs shots\n");
            delete prefs;
            return 1;
        }
        for (int i = 0; i < tabs->count(); ++i) {
            tabs->setCurrentIndex(i);
            app.processEvents();
            // Slugify the tab label for the filename (lower-case, spaces
            // to hyphens) so "Machine Learning" → "machine-learning".
            QString slug = tabs->tabText(i).toLower();
            slug.replace(QLatin1Char('&'), QString());
            slug.replace(QLatin1Char(' '), QLatin1Char('-'));
            const QString file = QStringLiteral("prefs-%1.png").arg(slug);
            if (!grabAndSave(prefs, QDir(outDir).filePath(file))) {
                delete prefs;
                return 1;
            }
        }
        delete prefs;
    }

    // G2 before/after evidence for the honest Wayland screenshot degrade.
    // Same File → Screenshot submenu, same state, two capability inputs:
    //   BEFORE — the Wayland user's OLD state: Whole Screen ENABLED (it looked
    //            actionable but silently produced a null/black PNG). Rendered
    //            with X11 inputs (platformName "xcb", not under a Wayland
    //            session), which is exactly the enabled path the pre-fix code
    //            took for a Wayland user because platformName was never
    //            consulted for the session.
    //   AFTER  — Whole Screen DISABLED with the honest tooltip. Rendered with
    //            Wayland inputs (under a Wayland session), the state the fix now
    //            produces for both native Wayland and XWayland.
    if (!grabCaptureMenu(app, target, QStringLiteral("xcb"), /*underWaylandSession=*/false,
                         QDir(outDir).filePath(QStringLiteral("wayland-capture-x11-enabled.png")))) {
        return 1;
    }
    if (!grabCaptureMenu(
            app, target, QStringLiteral("wayland"), /*underWaylandSession=*/true,
            QDir(outDir).filePath(QStringLiteral("wayland-capture-wayland-disabled.png")))) {
        return 1;
    }

    return 0;
}
