// grab_screenshots — produce reference PNGs of Trailer's main window
// states by driving Application + MainWindow under the offscreen Qt
// platform plugin. Used to populate docs/screenshots/ for the
// Windows documentation set without needing an active desktop session
// (works fine over SSH, in CI, etc.).
//
// Usage:
//   ./grab_screenshots <output-dir>
//
// On Windows the caller must set QT_QPA_FONTDIR=%SystemRoot%\Fonts so
// QPdfWriter has access to real PDF fonts; otherwise the fixture-PDF
// shot will show characters rendered as filled paths. See the comment
// in tests/uat/CMakeLists.txt for the longer explanation.
//
// Output files (under <output-dir>):
//   01-empty-window.png        empty MainWindow, no document loaded
//   02-pdf-loaded.png          fixture PDF loaded in the viewer
//
// The window is sized 1280x800 — a desktop-ish ratio that fits the
// toolbar + sidebar + viewer layout legibly while remaining portable
// across documentation surfaces.

#include "app/Application.h"
#include "ui/MainWindow.h"

#include <QDir>
#include <QElapsedTimer>
#include <QFileInfo>
#include <QImage>
#include <QPainter>
#include <QPageSize>
#include <QPdfWriter>
#include <QString>
#include <QStringList>
#include <QTemporaryDir>
#include <QThread>
#include <QTimer>
#include <cstdio>

namespace {

QString writeFixturePdf(const QString &path) {
    // Two-page A4 fixture with realistic-looking body text so the
    // resulting screenshot is recognisable as a document viewer.
    QPdfWriter writer(path);
    writer.setPageSize(QPageSize(QPageSize::A4));
    QPainter p(&writer);
    QFont title;
    title.setPointSize(28);
    title.setBold(true);
    p.setFont(title);
    p.drawText(300, 600, QStringLiteral("Trailer on Windows"));
    QFont body;
    body.setPointSize(14);
    p.setFont(body);
    p.drawText(300, 1000,
               QStringLiteral("A cross-platform PDF and image workbench."));
    p.drawText(300, 1300,
               QStringLiteral("This fixture is generated by tools/grab_screenshots."));
    writer.newPage();
    p.setFont(title);
    p.drawText(300, 600, QStringLiteral("Page 2"));
    p.setFont(body);
    p.drawText(300, 1000,
               QStringLiteral("Demonstrates multi-page navigation in the viewer."));
    p.end();
    return path;
}

// Pump the event loop until either `pred()` returns true or the
// timeout elapses. Used to wait for asynchronous side effects (PDF
// load → first paint, signal-driven layout updates) to settle before
// the grab. Returns true if `pred` ever returned true.
template <typename Pred> bool waitFor(Pred pred, int timeoutMs = 2000) {
    QElapsedTimer timer;
    timer.start();
    while (!pred() && timer.elapsed() < timeoutMs) {
        QCoreApplication::processEvents(QEventLoop::AllEvents, 50);
        QThread::msleep(10);
    }
    return pred();
}

bool grabAndSave(QWidget *w, const QString &outPath) {
    // One more spin so any pending paints flush through before grab.
    QCoreApplication::processEvents();
    const QPixmap pm = w->grab();
    if (pm.isNull()) {
        std::fprintf(stderr, "grab returned null pixmap for %s\n",
                     outPath.toLocal8Bit().constData());
        return false;
    }
    if (!pm.save(outPath)) {
        std::fprintf(stderr, "failed to write %s\n",
                     outPath.toLocal8Bit().constData());
        return false;
    }
    std::printf("wrote %s (%dx%d)\n",
                outPath.toLocal8Bit().constData(), pm.width(), pm.height());
    return true;
}

} // namespace

int main(int argc, char **argv) {
    if (argc < 2) {
        std::fprintf(stderr, "usage: %s <output-dir>\n", argv[0]);
        return 2;
    }
    const QString outDir = QString::fromUtf8(argv[1]);
    QDir().mkpath(outDir);

    trailer::Application app(argc, argv);
    Q_INIT_RESOURCE(trailer);

    // Fixture PDF lives in a QTemporaryDir cleaned up at exit.
    QTemporaryDir scratch;
    if (!scratch.isValid()) {
        std::fprintf(stderr, "failed to create scratch dir\n");
        return 1;
    }
    const QString fixturePath = writeFixturePdf(scratch.filePath("fixture.pdf"));

    auto *mw = app.ensureWindow();
    if (!mw) {
        std::fprintf(stderr, "ensureWindow() returned null\n");
        return 1;
    }
    mw->resize(1280, 800);
    app.processEvents();

    if (!grabAndSave(mw, QDir(outDir).filePath(QStringLiteral("01-empty-window.png")))) {
        return 1;
    }

    app.openFiles({fixturePath});

    // openFiles may spawn an additional window depending on the
    // user's OpenFilesIn preference. Find the most-recently-created
    // MainWindow (the one that just got the document) and wait for
    // QPdfDocument's asynchronous load + first paint cycle before we
    // grab. Without the wait the PDF render area is still blank,
    // making the "PDF loaded" screenshot indistinguishable from the
    // empty one.
    QWidget *target = mw;
    for (auto *w : trailer::Application::topLevelWidgets()) {
        if (auto *candidate = qobject_cast<trailer::MainWindow *>(w)) {
            candidate->resize(1280, 800);
            target = candidate;
        }
    }

    // Give the document time to load + render. QPdfDocument's lazy
    // page render lands on the GUI thread via signal so processEvents
    // alone is enough — the timeout is generous so a slow first-run
    // FreeType init doesn't make this flaky.
    waitFor(
        [target]() {
            return target->windowTitle().contains(QStringLiteral("fixture")) ||
                   target->windowTitle().contains(QStringLiteral("Trailer"));
        },
        3000);

    // One more grace period so QPdfView's pixmap caches populate.
    waitFor([] { return false; }, 500);

    if (!grabAndSave(target, QDir(outDir).filePath(QStringLiteral("02-pdf-loaded.png")))) {
        return 1;
    }

    return 0;
}
